# Generated by Django 4.2.2 on 2023-06-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_passing_year_usercard_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprivateinfo',
            name='user_email',
        ),
    ]
