JNV_MAP_LIST = {
        "BP":['Vidisha', 'Ashok Nagar', 'Betul', 'Bohani', 'Hatta', 'Jabalpur', 'Indore', 'Khurai', 'Mandsaur', 'Rampura', 'Shyampur', 'Seoni', 'Ratlam', 'Amarkantak', 'Burhanpur', 'Raigarh', 'Basdeif', 'Dantewada', 'Dhamtari', 'Durg', 'Jashpur', 'Kanker', 'Korba', 'Koriya', 'Mungeli', 'Khurdha', 'Hadgarh', 'Bagudi', 'Belpada, Balangir', 'Mundali', 'Narla, Kalahandi', 'Rayagada', 'Sambalpur', 'Sundargarh', 'Jharsuguda'],
        
        "CH":['Bilaspur', 'Dungrin', 'Kaza Lahul Spiti', 'Kinnaur', 'Kullu', 'Mandi', 'Kangra', 'Una', 'Sirmaur', 'Solan', 'Theog', 'Shopian', 'Jawahar Navodaya Vidyalaya Bandipora', 'Kupwara', 'Anantnag', 'Baramulla', 'Basohli', 'Doda', 'Ganderbal', 'Gharota', 'Budgam', 'Rajouri', 'Kulgam', 'Nud', 'Surankote', 'Udhampur', 'Pulwama', 'Chandigarh', 'Leh', 'Kargil', 'Awan, Amritsar I', 'Bathinda', 'Bring Khera', 'Kauni, Faridkot', 'Farour, Fatehgarh Sahib', 'Ferozepur', 'Najochak, Pathankot', 'Phalahi Hoshiarpur', 'Talwandi Madho, Jalandhar', 'Maseetan, Kapurthala', 'Lohara, Moga', 'Dhanansu,Ludhiana', 'Mansa', 'Patiala', 'Sandhuan, Ropar', 'Longowal, Sangrur', 'Pojewal Sbs Nagar,', 'Mohali', 'Lopoke, Amritsar-Ii', 'Dhilwan, Barnala'],
        
        "HB":['Middle Andaman', 'Car Nicobar', 'South Andaman', 'Anantpur, Hindupuram', 'East Godavari-2', 'Guntur', 'Kadapa', 'Prakasam', 'Peddapuram', 'Valasapalle', 'Veleru', 'West Godavari', 'Vizianagaram', 'Visakhapatnam', 'Bagalkote', 'Bangalore Rural', 'Bangalore Urban', 'Belagavi', 'Bellary', 'Bidar', 'Bijapur', 'Chamrajnagar', 'Chickmagalur', 'Chikkaballapura', 'Chitradurga', 'Dakshina Kannada', 'Davangare', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi - I', 'Kalaburagi - Ii', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shimoga', 'Tumkur', 'Udupi', 'Uttara Kannada', 'Yadgiri', 'Alappuzha', 'Chendayadu', 'Ernakulam', 'Idukki', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad', 'Minicoy', 'Karaikal', 'Mahe', 'Puducherry', 'Yanam', 'Adilabad', 'Karimnagar', 'Khammam', 'Mahabubnagar', 'Medak', 'Nalgonda', 'Nizamabad', 'Ranga Reddy', 'Warangal'],
        
        "JP":['Mungeshpur', 'Jaffarpur Kalan', 'Ambala', 'Bhiwani', 'Faridabad', 'Fatehabad', 'Gurgaon', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Mewat', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Jaipur', 'Karauli', 'Churu', 'Jaswantpura', 'Jojawar', 'Mandaphia', 'Patan', 'Nagaur', 'Atru (Baran)', 'Kherabad (Kota)', 'Pachpahar (Jhalawar)', 'Jhunjhunu'],
        
        "LK":['Raebareli', 'Gorakhpur', 'Kushinagar', 'Deoria', 'Ballia', 'Bhogaon', 'Mirzapur', 'Sitapur', 'Barabanki', 'Saharanpur', 'Sonbhadra', 'Sultanpur', 'Chandauli', 'Bareilly', 'Anaugi Kannauj', 'Jhansi', 'Jaunpur', 'Tarikhet', 'Rudrapur', 'Nainital', 'Haridwar', 'Champawat[1]', 'Pithoragarh', 'Chamoli', 'Rudraprayag', 'Tehri Garhwal', 'Pauri Garhwal', 'Dehradun', 'Uttarkashi', 'Bageshwar'],
        
        "PT":['Muzaffarpur', 'Jamui', 'Sheikhpura', 'Buxar', 'Bihiya', 'Supaul', 'Madhubani', 'Sitamarhi', 'West Champaran', 'Birauli,Samastipur', 'Boring Road,Patna', 'Shakti Nagar, Banka', 'Bokaro', 'Dhanbad', 'Koderma', 'Deoghar', 'Hazaribagh', 'Ranchi', 'Sahibganj', 'Ghaghra Gumla', 'Senha Lohardaga', 'Garhwa', 'Alipurduar', 'Bankura', 'Birbhum', 'Coochbehar', 'Hooghly', 'Durgapur', 'North 24 Parganas', 'South 24 Parganas', 'Dakshin Dinajpur', 'Uttar Dinajpur', 'Berhampur'],
        
        "PN":['Daman', 'Diu', 'Silvassa', 'Canacona', 'North Goa', 'Morbi', 'Gandhinagar', 'Amreli', 'Anand', 'Aravali', 'Banaskantha', 'Porbandar', 'Jamnagar', 'Patan', 'Kutch', 'Rajkot', 'Surendranagar', 'Borakhadi, Tapi', 'Junagadh', 'Mahisagar', 'Kagal, Kolhapur', 'Aurangabad', 'Ahmednagar', 'Nashik', 'Palghar', 'Tuljapur, Osmanabad', 'Buldhana', 'Satara', 'Amreli', 'Anand', 'Aravali', 'Banaskantha', 'Porbandar', 'Jamnagar', 'Patan', 'Kutch', 'Rajkot', 'Surendranagar', 'Borakhadi, Tapi', 'Junagadh', 'Mahisagar', 'Kagal, Kolhapur', 'Aurangabad', 'Ahmednagar', 'Nashik', 'Palghar', 'Tuljapur, Osmanabad', 'Buldhana', 'Satara', 'Bhusawal', 'Yavatmal', 'Amravati', 'Wardha', 'Partur, Jalna', 'Washim', 'Akola', 'Parbhani', 'Sindhudurg'],
        
        "SH":['Megdong', 'Dibrugarh', 'Karimganj', 'Golaghat', 'Bongaigaon', 'Jorhat', 'Pailapool', 'Sonitpur', 'Udalguri', 'Baksa', 'Darrang', 'Nalbari', 'Nagaon', 'Dhemaji', 'Goalpara', 'Diphu', 'Dima Hasao', 'Kokrakhar', 'Sivasagar', 'Morigoan', 'Karbi Anglong', 'West Karbi Anglong', 'Chachar', 'Chirang', 'Hailakhandi', 'Lakhimpur', 'Pfukhro Mao', 'Yaralpat', 'South Garo Hills', 'East Jaintia Hills', 'Champhai', 'Mokokchung', 'Phek', 'Mon', 'Kiphire', 'Dimapur', 'East Sikkim', 'West Sikkim', 'North Sikkim', 'South Sikkim', 'Dhalai', 'Dharmanagar', 'Gomati', 'North Tripura', 'Ramachandraghat', 'Khowai', 'Belonia South Tripura']
    }
STATES = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
    'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
    'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
    'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands',
    'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Ladakh',
    'Lakshadweep', 'Puducherry'
]
