# Generated by Django 4.2.2 on 2023-07-20 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='respondents',
            field=models.ManyToManyField(blank=True, related_name='filled_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='google_form_link',
            field=models.URLField(validators=[surveys.models.validate_survey_link]),
        ),
    ]
