# Generated by Django 4.2.2 on 2023-07-21 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_creator_survey_respondents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='survey',
            name='expire_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
