# Generated by Django 4.2.2 on 2023-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('broadcast_on', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BroadcastNotification',
                'verbose_name_plural': 'BroadcastNotifications',
                'ordering': ['-broadcast_on'],
                'managed': True,
            },
        ),
    ]
