# Generated by Django 4.2.2 on 2023-07-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={'ordering': ['-broadcast_on']},
        ),
    ]
