# Generated by Django 4.2.2 on 2023-07-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['user', '-timestamp']},
        ),
    ]
