# Generated by Django 4.2.2 on 2023-07-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
