# Generated by Django 4.2.2 on 2023-06-18 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to=settings.AUTH_USER_MODEL)),
                ('refers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('help_type', models.CharField(choices=[('U', 'Urgent'), ('H', 'High Priority'), ('N', 'Normal')], max_length=1)),
                ('status', models.CharField(choices=[('S', 'Sent to All'), ('H', 'On Hold'), ('C', 'Complete')], max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField()),
                ('users_affected', models.ManyToManyField(related_name='affected_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.help')),
                ('referred_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_events', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
