# Generated by Django 4.2.2 on 2023-06-18 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pairuser',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='pairuser',
            name='refers',
        ),
        migrations.RemoveField(
            model_name='help',
            name='users_affected',
        ),
        migrations.AddField(
            model_name='help',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_helps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='help',
            name='deleted_by',
            field=models.ManyToManyField(related_name='deleted_helps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='help',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PairUser',
        ),
        migrations.AddField(
            model_name='referral',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.help'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_users', to='helper.help'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='help',
            name='referred_to',
            field=models.ManyToManyField(blank=True, through='helper.Referral', to='helper.help'),
        ),
    ]
