# Generated by Django 4.2.2 on 2023-06-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_deleted',
        ),
    ]
