# Generated by Django 4.2.2 on 2023-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_remove_request_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
