# Generated by Django 4.2.2 on 2023-06-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_request_location_request_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='deletion_date',
            new_name='deletion_at',
        ),
    ]
