# Generated by Django 4.2.2 on 2023-07-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_rename_deletion_date_request_deletion_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
