# Generated by Django 4.2.2 on 2023-07-21 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helper', '0006_comment_email_comment_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
