# Generated by Django 4.2.2 on 2023-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_request_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
