# Generated by Django 4.2.2 on 2023-08-13 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('verification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
